# Generated by Django 2.2.3 on 2019-07-24 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='query',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Query'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 12, 54, 31, 968495)),
        ),
    ]
